apiVersion: v1
kind: Service
metadata:
  name: ai-elder-care-agent
spec:
  selector:
    app: ai-elder-care-agent
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer